name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build base container
        uses: docker/build-push-action@v6
        with:
          # load: true
          push: true
          file: api.Dockerfile
          tags: ghcr.io/cronun/backend-api:latest

      # - name: Test
      #   run: |
      #     docker run --rm ${{ env.TEST_TAG }}
